DOMAIN = "pet_marvel"
MANUFACTURER = "Pet Marvel"
VALID_COUNTRY_TO_CODE_MAPPING = {
    "Australia": "61",
    "Austria": "43",
    "Belgium": "32",
    "Canada": "1",
    "China": "86",
    "Denmark": "45",
    "Finland": "358",
    "France": "33",
    "Germany": "49",
    "Hong Kong": "852",
    "Ireland": "353",
    "Italy": "39",
    "Japan": "81",
    "Macao": "853",
    "Malaysia": "60",
    "Netherlands": "31",
    "New Zealand": "64",
    "Norway": "47",
    "Poland": "48",
    "Singapore": "65",
    "South Korea": "82",
    "Spain": "34",
    "Sweden": "46",
    "Switzerland": "41",
    "Taiwan": "886",
    "Thailand": "66",
    "United Kingdom": "44",
    "United States": "1",
    "Vietnam": "84",
}
